repos:
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: ['--max-line-length=120', '--ignore=E501,W503']
        files: ^deploy_workloads\.py$

  - repo: local
    hooks:
      - id: tox
        name: Run tox tests
        entry: tox
        language: system
        pass_filenames: false
        always_run: true
