apiVersion: ramendr.openshift.io/v1alpha1
kind: Recipe
metadata:
  name: cli-c6-imp-busybox-rbd-rp-4-cg
spec:
  appType: busybox
  groups:
  - backupRef: cli-c6-imp-busybox-rbd-rp-4-cg
    excludedResourceTypes:
    - events
    - event.events.k8s.io
    - persistentvolumes
    - replicaset
    - persistentvolumeclaims
    - pods
    includedNamespaces:
    - cli-c6-imp-busybox-rbd-rp-4-cg
    labelSelector:
      matchExpressions:
      - key: workloadpattern
        operator: In
        values:
        - simple_io
    name: cli-c6-imp-busybox-rbd-rp-4-cg
    type: resource
  hooks:
  - chks:
    - condition: '{$.spec.replicas} == {$.status.readyReplicas}'
      name: stateReady
      onError: fail
      timeout: 900
    name: deployment-check
    nameSelector: busybox-*
    namespace: cli-c6-imp-busybox-rbd-rp-4-cg
    onError: fail
    selectResource: deployment
    timeout: 800
    type: check
  volumes:
    includedNamespaces:
    - cli-c6-imp-busybox-rbd-rp-4-cg
    labelSelector:
      matchExpressions:
      - key: workloadpattern
        operator: In
        values:
        - simple_io_pvc
    name: mypvc
    type: volume
  workflows:
  - failOn: any-error
    name: backup
    sequence:
    - hook: deployment-check/stateReady
    - group: cli-c6-imp-busybox-rbd-rp-4-cg
  - failOn: any-error
    name: restore
    sequence:
    - group: cli-c6-imp-busybox-rbd-rp-4-cg
    - hook: deployment-check/stateReady
