apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: PLACEHOLDER-4
  namespace: openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: PLACEHOLDER-4-placement
        requeueAfterSeconds: 180
  template:
    metadata:
      name: PLACEHOLDER-4-{{name}}
      annotations:
        apps.open-cluster-management.io/ocm-managed-cluster: "{{name}}"
        apps.open-cluster-management.io/ocm-managed-cluster-app-namespace: openshift-gitops
        argocd.argoproj.io/skip-reconcile: "true"
      labels:
        velero.io/exclude-from-backup: "true"
        apps.open-cluster-management.io/pull-to-ocm-managed-cluster: "true"
    spec:
      project: default
      sources:
        - repositoryType: git
          repoURL: https://github.com/red-hat-storage/ocs-workloads.git
          targetRevision: less_workload_rbd
          path: rdr/busybox/rbd/workloads/app-busybox-1
      destination:
        namespace: PLACEHOLDER-4
        server: "{{server}}"
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true
          - PruneLast=true
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: PLACEHOLDER-4-placement
  namespace: openshift-gitops
spec:
  numberOfClusters: 1
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: name
              operator: In
              values:
                - prsurve-c1x
  clusterSets:
    - clusterset-submariner-44dd33a3710d4cfc96
---
apiVersion: ramendr.openshift.io/v1alpha1
kind: DRPlacementControl
metadata:
  name: busybox-placement-drpc
  namespace: openshift-gitops
spec:
  drPolicyRef:
    apiVersion: ramendr.openshift.io/v1alpha1
    kind: DRPolicy
    name: drpolicy-5m
  placementRef:
    apiVersion: cluster.open-cluster-management.io/v1beta1
    kind: Placement
    name: busybox-placement
    namespace: openshift-gitops
  preferredCluster: prsurve-c1u
  pvcSelector:
    matchExpressions:
      - key: workloadpattern
        operator: In
        values:
        - simple_io_pvc